#!/bin/bash

stackName="ha-ecs"
regions="us-east-1 us-east-2 us-west-1 us-west-2 eu-west-1 eu-west-2 eu-central-1 ap-northeast-1 ap-southeast-1 ap-southeast-2 ca-central-1"

for region in $regions; do
  aws cloudformation update-stack \
    --stack-name $stackName \
    --capabilities CAPABILITY_IAM \
    --template-body file://master.yaml \
    --region $region

  aws cloudformation wait stack-update-complete \
    --stack-name $stackName \
    --region $region &
done